title: 13S Docs
description: clang vs. gcc
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

url: https://sneha-afk.github.io/13s-docs-by-sneha/


callouts:
  warning:
    title: Warning
    color: red
  tip:
      title: Tip
      color: yellow
  note:
    title: Note
    color: blue

heading_anchors: true
