title: 13S Docs
description: clang vs. gcc
theme: just-the-docs

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

url: https://sneha-afk.github.io/13s-docs


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Tip
    color: purple
  warning:
    title: Warning
    color: red

heading_anchors: true

# Footer stuff

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "See source on GitHub"
gh_edit_repository: "https://github.com/sneha-afk/13s-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
